name: Django Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Unit Test
        env:
          SECRET_KEY: qf6b9t#)en32989p#hleh8v9)8@*ga4g1di%5p%-#0i$6qbzzo
          DEBUG: True
          AWS_ACCESS_KEY_ID: AKIA54IURWVMYKBWFXFT
          AWS_SECRET_ACCESS_KEY: 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
          AWS_STORAGE_BUCKET_NAME: djangodocker
        run: |
          python manage.py test
      - name: Coverage report
        run: |
          coverage run manage.py test
          coverage report
